Repository milieuinfo/webcomponent-vl-ui-infoblock, pull requests merged in 2020-06, with the labels that each got.

#30 getIcon is depracated, overschakelen naar getType
  .eslintrc.json
  CODEOWNERS
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
  test/e2e/infoblock.test.js
Labels: bugfix

#32 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-infoblock.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/vl-infoblock.js
  test/e2e/components/vl-infoblock.js
  test/e2e/infoblock.test.js
  test/e2e/pages/vl-infoblock.page.js
  test/unit/vl-infoblock.test.html
Labels: chore

#33 Importeer sinon vanuit node_modules voor de unit testen
  package-lock.json
  test/e2e/infoblock.test.js
Labels: bugfix

#36 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
Labels: bug

#38 Deduplicatie NPM run scripts Update naar latest vl-ui-util en vl-ui-core
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
