Repository milieuinfo/webcomponent-vl-ui-infoblock, pull requests merged in 2020-01, with the labels that each got.

#3 Gelijkzetten met nieuwe test opzet en introductie e2e testen
  .mocharc.js
  README.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  demo/vl-infoblock.html
  index.js
  package-lock.json
  package.json
  test/docker-compose.yml
  test/e2e/components/vl-infoblock.js
  test/e2e/infoblock.test.js
  test/e2e/pages/vl-infoblock.page.js
  test/unit/vl-infoblock.test.html
  test/wct.docker.conf.json
  wct.docker.conf.json
  wct.local.conf.json
Labels: chore

#4 Fix getText() methode zodat enkel de textContent getoond word. Anders word het titel-attribuut mee afgedrukt
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
  test/e2e/components/vl-infoblock.js
  test/e2e/infoblock.test.js
Labels: bugfix

#5 Update util en package-lock
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
Labels: bugfix

#8 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#6 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#7 Update vl-ui-util
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
Labels: maintenance

#9 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#10 Update naar laatste util
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  style.css
  style.css.map
Labels: chore

#11 Update naar laatste util
  test/e2e/infoblock.test.js
Labels: chore

#12 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  docker-compose-release.yml
  package-lock.json
  package.json
  style.css
  style.css.map
Labels: maintenance
